// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxcbbkqcrvknuzxglwin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4Y2Jia3FjcnZrbnV6eGdsd2luIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0OTY3MDksImV4cCI6MjA1ODA3MjcwOX0.-tTXf_ZkZLtAs1V2U8O_xT0dpdUR36N-6ZFCI72vGFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);